### ISSUE TITLE
track_id 

### ISSUE THREAD

**Issue by xfchangwei** [xiaomingnio/MCByteTrack#1]
感谢您的贡献，我运行似乎有点小问题，不同类别的track_id不是重新计数的，而是累加的，比如出现一个人，和一部手机，人的track_id 为1，手机的track_id 为2.

**Comment by LumenForgeX** [comment]
目前是把不同的track_id视作不同的个体，一个简单的处理方式是：得到结果后根据每类别重新赋值id。
